# Generated by Django 5.0.7 on 2024-07-24 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="parent",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="menu.menu"
            ),
        ),
    ]
